version: "2.1"# docker-compose version
services:
  flask-app:
    build: flask-app # look for it in flask_app directory
    #restart: always # always spins up the flask container even when there is a failure
    ports:
      - 5000:5000
    networks:
      - my_flask_network # specify the network where the flask and nginx will connect in

  nginx:
    build: nginx
    #restart: always
    ports:
      - 80:80
    networks:
      - my_flask_network # both containers need to be in the same network

networks:
  my_flask_network:






















version: "1.25" # docker-compose version
services:
  flask-app:
    build: ./flask_app # look for it in flask_app directory
		restart: always # always spins up the flask container even when there is a failure
    #ADD THIS /
    volumes:
      - static_volume:/home/app/web/project/
      - media_volume:/home/app/web/project/media
    ports:
      - 5000:5000
    environment:
      - DEBUG :0  # enable or disable debug mode
		networks:
      - my_flask_network # specify the network where the flask and nginx will connect in

  nginx:
    build: ./nginx
		restart: always
    #ADD THIS /
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media


    ports:
      - 80:80
    depends_on:
      - flask-app
    networks:
      - my_flask_network # both containers need to be in the same network

networks:
  my_flask_network:
