version: "2.1"# docker-compose version
services:
  flask-app:
    build: flask-app # look for it in flask_app directory
    #restart: always # always spins up the flask container even when there is a failure
    ports:
      - 5000:5000
    networks:
      - my_flask_network # specify the network where the flask and nginx will connect in

  nginx:
    build: nginx
    #restart: always
    ports:
      - 80:80
    networks:
      - my_flask_network # both containers need to be in the same network

networks:
  my_flask_network:


















